### ISSUE TITLE
Police Cosmetic Shop

### ISSUE THREAD

**Issue by Rease1** [LastNickLeft/Illicit-Gaming---Requests-and-issues#10]
**PCSO** 
PCSO Uniform 
Police Cap
Tactical Vest
All Normal Shades
Tinted Spectacles
Carryall

**Comment by Rease1** [comment]
**PC** 
Patrol Uniform 
Police Cap
Tactical Vest
All Normal Shades
Tinted Spectacles
Black Beret

**Comment by Rease1** [comment]
**SPC** 
Patrol Uniform 
Police Cap
Tactical Vest
Carrier Lite
All Normal Shades
Tinted Spectacles
Black Beret
Normal Beanie

**Comment by Rease1** [comment]
**SGT** 
Patrol Uniform 
Police Cap
Tactical Vest
Carrier Lite
All Normal Shades
Tinted Spectacles
Black Beret
Normal Beanie
Boonie Hat
Balaclava Black

**Comment by Rease1** [comment]
**INS** 
Patrol Uniform 
Police Cap
Tactical Vest
Carrier Lite
All Normal Shades
Tinted Spectacles
Black Beret
Normal Beanie
Boonie Hat
Balaclava Black 
Light Combat Helmet (Black)

**Comment by Rease1** [comment]
**DI** 
Patrol Uniform 
Police Cap
Tactical Vest
Carrier Lite
All Normal Shades
Tinted Spectacles
Black Beret
Normal Beanie
Boonie Hat
Balaclava Black 
Light Combat Helmet (Black)
Rangemaster Hat

**Comment by Rease1** [comment]
**DI** 
Patrol Uniform 
Police Cap
Tactical Vest
Carrier Lite
All Normal Shades
Tinted Spectacles
Black Beret
Normal Beanie
Boonie Hat
Balaclava Black 
Light Combat Helmet (Black)
Rangemaster Hat
Beret (Genedarmerie)

**Comment by Rease1** [comment]
**CI** 
Patrol Uniform 
Police Cap
Tactical Vest
Carrier Lite
All Normal Shades
Tinted Spectacles
Black Beret
Normal Beanie
Boonie Hat
Balaclava Black 
Light Combat Helmet (Black)
Rangemaster Hat
Beret (Genedarmerie)

**Comment by Rease1** [comment]
**CI**
Patrol Uniform
Police Cap
Tactical Vest
Carrier Lite
All Normal Shades
Tinted Spectacles
Black Beret
Normal Beanie
Boonie Hat
Balaclava Black
Light Combat Helmet (Black)
Rangemaster Hat
Beret (Gendarmerie)

**Comment by Rease1** [comment]
SI
Patrol Uniform
Police Cap
Tactical Vest
Carrier Lite
All Normal Shades
Tinted Spectacles
Black Beret
Normal Beanie
Boonie Hat
Balaclava Black
Light Combat Helmet (Black)
Rangemaster Hat
Beret (Gendarmerie)
Beret [NATO]
Berert [NATO] Colonel
Marshall Cap

**Comment by bgill678** [comment]
PCSO DONE

**Comment by bgill678** [comment]
PC DONE

**Comment by bgill678** [comment]
SPC DONE

**Comment by bgill678** [comment]
SGT DONE

**Comment by bgill678** [comment]
INS DONE

**Comment by bgill678** [comment]
DI

**Comment by bgill678** [comment]
CI

**Comment by bgill678** [comment]
SI

**Comment by bgill678** [comment]
CSI

**Comment by bgill678** [comment]
Done
