### ISSUE TITLE
TFU shit (dont delete u dead ass)

### ISSUE THREAD

**Issue by ma1k0** [LastNickLeft/Illicit-Gaming---Requests-and-issues#13]
All of the Bandanas (Facemasks) (Added)
All 3 Respirators (Yellow, White and Blue) (Added)
Pilot Helmet [NATO] (Added)
Wireless Earpiece (Added)
Marshall Cap (Added)
Cap (Blue) (Added)
Cap (Red) (Added)
Cap (US Black) (Added)
(Hat) Bandana Black (Added)
Cap (White) IDAP (Added)
Cap (Black) IDAP (Added)
Cap (Orange) IDAP (Added)
Full Ghilie NATO (Lush) (Added)
Full Ghilie NATO (Semi-Arid) (Added)
LIM-85 (Added)
AK-12 (Added)
SPAR-17 (Added)
MAR-10 Mags (Added)
GA Carrier GL Rig (Digi) (Added)
Flashbangs (Added)

**Comment by Rease1** [comment]
No Mar 10 
No Ghillie
No Lim yet couple weeks after we get going 
no pilot helmet

**Comment by bgill678** [comment]
I'll do this tomorrow

**Comment by bgill678** [comment]
All Done, no LOW DLC Content available on the main biWiki for some reason, either it's me being blind or them being incompetent as usual. But anyway yeah all done, closing issue.
