### ISSUE TITLE
New TFU Equipment & Accessories

### ISSUE THREAD

**Issue by ma1k0** [LastNickLeft/Illicit-Gaming---Requests-and-issues#3]
-------------------------------------------------------------------------------------------------------------------
If you feel like any of these items need to be discussed before adding/removing please message me or @Rease1 
-------------------------------------------------------------------------------------------------------------------
Please can TFU have these items (removed) and (added) to their shop:
-------------------------------------------------------------------------------------------------------------------
All of the Bandanas (Facemasks) (Added)
All 3 Respirators (Yellow, White and Blue) (Added)
Pilot Helmet [NATO] (Added)
Wireless Earpiece (Added)
Marshall Cap (Added)
Cap (Blue) (Added)
Cap (Red) (Added)
Cap (US Black) (Added)
(Hat) Bandana Black (Added)
Cap (White) IDAP (Added)
Cap (Black) IDAP (Added)
Cap (Orange) IDAP (Added)
US Assault Pack (Kerry) (Added)
Full Ghilie NATO (Lush) (Added)
Full Ghilie NATO (Semi-Arid) (Added)
Full Ghilie NATO (Jungle) (Added)
Full Ghilie NATO (Arid) (Added)
LIM-85 (Added)
ASP-Kir (Added)
AK-12 (Added)
SPAR-17 (Added)
MAR-10 Mags (Added)
Orca with skin (Added)
GA Carrier GL Rig (Digi) (Added)
Flashbangs (Added)
-------------------------------------------------------------------------------------------------------------------
_MK-20 (Removed)
Sting  (Removed)
Vermin (Removed)
Blackfoot (Removed)
Marshall (Removed)
Ghosthawk (Removed)
All pistols except the Tazer (Removed)_
-------------------------------------------------------------------------------------------------------------------
New Hunter Skin (To be discussed)
New Clothing Skin (To be discussed)
New TFU base (To be discussed)
-------------------------------------------------------------------------------------------------------------------

**Comment by LastNickLeft** [comment]
MK-20 (Removed)  ✓
Sting (Removed) ✓
Vermin (Removed) ✓
Blackfoot (Removed) ✓
Marshall (Removed) ✓
Ghosthawk (Removed) ✓
All pistols except the Tazer (Removed) ✓

**Comment by LastNickLeft** [comment]
Orca + Texture added
Hatchback and SUV + Texture added
