### ISSUE TITLE
Police Uniforms

### ISSUE THREAD

**Issue by Rease1** [LastNickLeft/Illicit-Gaming---Requests-and-issues#8]
Make the normal patrol uniform the command uniform
Make a new normal patrol uniform with a dark blue top and black trousers (same AAF clothes like the command one, not the jumper.
PCSO uniform can look the same but just on the AAF clothes not that NATO ones 
NPAS clothes are CSATs make them the nato coveralls :)
and remove the SGT logo from the shoulder of uniforms and just put a UK flag there or something.

**Comment by bgill678** [comment]
@LastNickLeft

**Comment by bgill678** [comment]
@LastNickLeft

**Comment by LastNickLeft** [comment]
I'm not redoing NPAS uniform, it's fine as it is.

However I've updated PCSO uniform and set current command uniform as Police Patrol uniform. I've made a few edits to it.. SGT insignia is gone and it has been replaced with HM crown

**Comment by Rease1** [comment]
yes put the npas uniform is CSAT fatigues meaning it has a lot of armour so they are really op @LastNickLeft

**Comment by Rease1** [comment]
@LastNickLeft  [![Screenshot from Gyazo](https://gyazo.com/7208afc1eccd7ccfc424e72afd08729a/raw)](https://gyazo.com/7208afc1eccd7ccfc424e72afd08729a)
