### ISSUE TITLE
Police Icons in game

### ISSUE THREAD

**Issue by Rease1** [LastNickLeft/Illicit-Gaming---Requests-and-issues#9]
https://drive.google.com/drive/folders/1YHeG0E2p5uHSY2NGK4vUoB7n91aQQddP
all images 64x64 in that folder already compressed
Rank names are as follows as some were spelt wrong
Chief Superintendent
Superintendent
Chief Inspector
Detective Inspector
Inspector
Sergeant
Senior Police Constable
Police Constable
Police Community Support Officer

**Comment by bgill678** [comment]
Argh, png's

**Comment by bgill678** [comment]
Where is PCSO?

**Comment by bgill678** [comment]
Update?

**Comment by bgill678** [comment]
@Rease1

**Comment by Rease1** [comment]
my bad ill whip up pcso now

**Comment by Rease1** [comment]
done @bgill678
